apiVersion: apps/v1
kind: Deployment
metadata:
  name: raj-app-meta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: raj-app
  template:
    metadata:
      labels:
        app: raj-app
       
    spec:
      containers:
      - name: raj-app
        image: harshii0520/grievance-project-app:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/raj-app"
        - name: PORT
          value: "5000"
        - name: HOST
          value: "0.0.0.0"
        - name: NODE_ENV
          value: "production"
 
---
apiVersion: v1
kind: Service
metadata:
  name: raj-app-service
spec:
  selector:
    app: raj-app
  ports:
  - port: 80
    targetPort: 3001
  type: LoadBalancer
 